project:
  type: book

book:
  title: "NISA-book"
  author: "NISA - Network Information Security Association"
  date: "2024/12/13"
  chapters:
    - index.qmd
    - part: CTF - 夺旗赛
      chapters: 
        - CTF/intro.qmd
        - CTF/Crypto.md
        - CTF/Misc/intro.qmd
        - CTF/Misc/Password Crack.qmd
        - CTF/Misc/Compressed File.qmd
        - CTF/Misc/Steganography.qmd
        - CTF/Pwn.qmd
        - CTF/Reverse.qmd
        - CTF/Web.qmd
    - part: Penetration - 渗透测试
      chapters:
        - Penetration/intro.qmd
        - Penetration/Privilege Escalation.qmd
    - part: Forensic - 电子取证
      chapters: 
        - Forensic/intro.qmd
        - Forensic/tools.qmd
    - part: Incident Response - 应急响应
      chapters: 
        - Incident Response/intro.qmd
    - part: Attack Defense - 红蓝攻防
      chapters: 
        - Attack Defense/intro.qmd
    - part: DevSecOps - 开发、安全和运维
      chapters:
        - DevSecOps/intro.qmd
        - DevSecOps/Software Supply Chain Security.qmd
        - DevSecOps/CI-CD.qmd
    - part: ICS - 工业安全
      chapters: 
        - ICS/intro.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrbook
    # classoption: oneside # 强制使用单面模式
    geometry:
    - top=20mm
    - left=20mm
    - bottom=20mm
    - right=20mm
    # keep-tex: true

    include-in-header: 
      text: |
        \usepackage{ctex}
        \usepackage{amsthm,mathrsfs}
        \usepackage{graphicx}
        \usepackage{fancyhdr}
        \usepackage{fvextra}
        
        \pagestyle{fancy}
        \fancyhf{}  % 清空默认页眉页脚
        \setlength{\footskip}{12mm}  % 调整页脚高度

        % 设置奇偶页的页脚格式，页码和章节信息在同一侧
        \fancyfoot[LE]{\thepage\quad\rightmark} % 偶数页左侧显示页码+章节信息
        \fancyfoot[RO]{\rightmark\quad\thepage}  % 奇数页右侧显示章节信息+页码
        
        % 自定义章节信息的显示方式
        \renewcommand{\chaptermark}[1]{\markboth{\chaptername\ \thechapter\ #1}{}}

        % 强制在章节标题后添加首行缩进
        \usepackage{indentfirst}  % 使每段第一行都缩进
        \setlength{\parindent}{2em}  % 设置缩进宽度，可以根据需要调整

        % 代码块换行
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
        \DefineVerbatimEnvironment{OutputCode}{Verbatim}{breaklines,commandchars=\\\{\}}