# CTF 概述

CTF(Capture The Flag) 是一种在网络安全领域常见的一种竞赛形式，其核心为 Jeopardy 形式，即题目提供环境或者附件作为问题，选手需要对环境或者附件进行操作，解题目标是得到问题中所包含的答案，常见的格式为 `flag{This_is_Flag}` 字符串，这个由 `flag` 头部以及大括号组成的字符串也就是问题的答案，也称为 flag 旗帜。

## 方向介绍

传统的 CTF 竞赛可以分为五大方向：

```plaintext
Crypto, Misc, Pwn, Reverse, Web
```

**Crypto** - Cryptography 即密码学，编码、加密信息的过程与逆过程。密码学的大规模利用可以追溯到战争中的信息传递，最广为人知的就是二战期间所出现的恩尼格玛（Enigma）密码机，到了现代，传统的代换密码（单表代换和多表代换）以及各种各种图形密码所代表的古典密码学已经形同虚设，随之而来的便是现代密码学体系。

**Misc** - Miscellaneous 即杂项，在传统的 Misc 方向题目中常见的题型有密码破解、信息隐写、电子取证以及一系列新型技术。在一些比较新的 CTF 竞赛中，像是隐写（Steganography）和取证（Forensic）都已经被独立为单独的方向，Misc 方向更多的是新出现的漏洞以及较前沿的技术研究。

**Pwn** 即二进制漏洞攻击，不同于二进制逆向，Pwn 更多的是基于程序本身的漏洞直接进行攻击，进而取得目标环境的权限。

**Reverse** 即二进制程序逆向，是直接对二进制形式的程序样本直接进行分析，利用逆向工具将程序中的二进制信息反编译为汇编语言，亦反汇编得到程序运行逻辑的伪代码，进而对程序运行流程进行分析，探寻其运行逻辑

**Web** 即互联网应用安全，主要研究基于互联网应用的安全问题。Web 方向的题目通常围绕常见的 Web 技术（如 HTML、JavaScript、PHP 等）和协议（如 HTTP、HTTPS）展开，测试参赛者对 Web 应用程序的安全漏洞的发现与利用能力。

随着时代发展，也逐渐有新的方向被创建或从传统五大方向中拆分出来，其中较为常见的有

```plaintext
AI, Blockchains, Forensic, Hardware, Mobile, Osint, Pentest, PPC, Steganography
```

**AI** 即人工智能

**Blockchains** 即区块链

**Forensic** 即取证

**Hardware** 即硬件分析

**Mobile** 即移动安全

**Osint** 即社工分析

**Pentest** - Penetration 即渗透测试

**PPC** - Professionally Program Coder 即编程开发

**Steganography** 即隐写技术

可以看出，大部分新型方向都是由原本的 Misc 方向拆分出来，这也说明了 Misc 虽然在前期入门时较为有趣，学习难度较低，但是后续的学习内容和涵盖的技能复杂性都要远远高于其他方向。
