# 电子取证概述

电子取证，顾名思义，就是针对电子设备中的证据数据进行提取，并加以分析。根据取材的类型不同，可以分为磁盘取证，内存取证，流量分析等等；而根据目标设备的不同类型，可以分为 Windows 取证，Linux 取证，安卓设备取证，苹果设备取证等等。

对于电子取证而言，其实在入门阶段就存在一定的门槛，因为不同于常规的 CTF 方向，电子取证具有较高的数据敏感性和专业性，并且在常规的 CTF 竞赛中，电子取证的出场率和分数占比也不高，所以电子取证其实并没有被大多数选手所重视。但近些年，随着各大电子取证比赛降低门槛，邀请 (允许) 非警校的院校参加，而且 CTF 近几年的题目趋势越来越接近实战，电子取证在 CTF 竞赛中也逐渐占有了一席之地。

但同时也需要明白，都说大学里面只学了 CTF 以后毕业不好找工作，那么取证其实是更尴尬的位置，如果不是有相关专业或者警校这类强相关的环境，否则取证并不能给你以后的工作提供太大的帮助。

## 内存取证

内存为易失性储存设备，电子设备在断电后的短时间内，内存中就会丢失数据，从而失去分析价值；但是随着技术的进步，只要在设备断电后快速将内存卸下，并接入专用设备，也可以从残留的数据中提取证据。更何况大部分情况下，取证人员可以直接在现场，保持设备通电开机的情况下，直接对目标设备的内存进行取证工作，从而给完整提取目标设备的内存数据提供了机会。

不同于直接对硬盘、手机、储存卡等设备进行取证，内存取证由于其为设备的内存数据，其天生就为电子取证的重要一点：因为设备在运行中，凡是涉及到数据的解析，在内存中大多都是以中间态或最后的明文态而存在；而在硬盘等设备中，数据可以进行加密，进行混淆，就大大增加了分析难度。故在电子取证中，内存取证往往为最为重要的一环。

## 磁盘取证

磁盘取证分析，是指对磁盘上的原始数据进行取证分析。磁盘数据存在多种分区方案，例如 FAT32，NTFS，EXT 系列，ZFS，exFAT 等等，不同的分区方案需要用不同的方式进行读取，才能正确读取到数据。同时，由于不同的分区方案有着不同的数据结构和分区表形式，如果涉及到磁盘数据损坏，还要考虑到分区表损坏的情形，那就要更进一步，涉及到数据恢复的领域。

单单对于磁盘数据的处理和分析的话，可以考虑使用相关的磁盘管理和维护工具，例如 Diskgenius，对于原始磁盘镜像的读取和挂载，可以使用 FTK Imager，而对磁盘的原始扇区数据进行读取，以及查看分区表数据等操作，可以使用 DIskgenius 等磁盘管理工具。

对磁盘上的数据进行取证分析，常用的开源两件套是 Autopsy 和 FTK imager，Autopsy 可以对磁盘数据进行静态分析，而 FTK imager 可以直接浏览磁盘的原始数据，并支持将磁盘镜像文件进行挂载，二者相结合可以满足磁盘取证分析的基本要求

### 磁盘阵列

Raid，即 Redundant Arrays of Independent Disks，数块独立磁盘构成的具有冗余能力的阵列。通过构建 Raid 整列，可以将多块独立的物理硬盘整合为一个储存池，在便于管理的同时，可以提供比单块硬盘更加优秀的读写性能和风险冗余能力。但是 on the other hand，在提供多种高级特性的同时，阵列也是脆弱的，一旦多块硬盘同时发生数据校验错误，就可能发生阵列严重性错误，最终导致即使其他硬盘的工作状态完好，也无法再将数据提取出来，也就是直接火葬场。所以，在电子取证领域，数据恢复也是一大难题。

## 仿真取证

不同于使用工具直接对数据镜像进行分析，仿真取证是从数据镜像中还原出目标设备的原始环境，然后模拟出直接在目标设备上进行操作的环境。为了保护目标设备上的数据不得篡改，防止证据被破坏，取证分析人员不会直接在目标设备上直接进行操作，而是提取镜像之后进行仿真取证。仿真取证具有静态取证分析不可比拟的优越性：快速、直观且直接。通过仿真的方式进行取证分析，分析人员可以模拟直接与目标设备进行交互，进而快速探测目标设备上的具体情况，进而可以与静态取证分析相结合，大大增加取证分析的效率；并且通过模拟直接与目标设备进行交互，可以绕过繁琐的数据静态分析，从而直接查看数据，例如查看浏览器的历史记录、浏览邮件往来、访问笔记软件中的页面等等。

仿真取证看似美好，但是受到检材格式的约束：部分检材的格式为虚拟磁盘文件，那么说明极大概率得到的检材为虚拟机提取出来的，就可以直接导入相对应的虚拟机软件中尝试直接启动；而对于像 .raw、.e01 和 .dd 等格式的原始磁盘数据镜像文件，能否进行仿真取证很大程度上取决于提取出来的分区数据中是否包含有启动分区，若没有启动分区数据，则很难进行仿真取证。但是，没有启动分区数据也并非代表不能进行仿真取证：取证分析人员在分析磁盘上存在的系统种类之后，可以尝试使用现有的启动分区 (如直接拷贝物理 Windows 环境中的启动分区) ，进而尝试进行仿真取证。

## 流量分析

按照一般的理解，流量分析应该是直接放在 Misc 里面的，电子取证只涉及对内存数据和磁盘数据的取证分析。但是，电子取证其本身就是对电子设备的数据进行取证分析，而流量数据其分析重要性和内存、磁盘数据是不相上下的，三者往往相互辅助，共同辅助构建目标设备的时间线痕迹的分析结果。

## 商业软件与开源方案

在磁盘取证中，我们已经接触到了开源方案：Autopsy 和商业软件：取证大师，火眼证据分析 等等，可以发现无论是支持分析的痕迹种类，运行速度等等指标，商业软件都要比开源方案好上不少。那么孰优孰劣呢？在允许的情况下 (自身可以从正规渠道取得相关公司的软件许可) ，建议还是使用商业软件来进行取证工作，以大大方便取证工作的开展。

但是怀揣着开源精神，从一定角度上来讲，商业软件也并非绝对机密，它们的相关功能均可以从开源代码中找到相关的同等效果实现，例如 取证大师 的内存分析工具，其中就是用到了 Volatility 2 相关开源运行库，而相关浏览器痕迹分析 (chromium 类和 Firefox 类浏览器中的浏览历史、页面缓存、用户保存的密码等等) 也可以找到相关开源代码。所以在无法取得相关商业软件授权的情况下，也不必灰心，完全可以依赖开源代码和自己的手速，来实现同等的效果 ( 没那么快就是了 )

国外的破解版软件也很香啊，比如 Passware Kit 和 AXIOM，既快又好用，前提是能找到没有私货的破解版

目前在国内，主流使用的商业取证软件可以分为三家，分别是美亚柏科 (取证大师) 、弘连网络 ( 火眼证据分析 ) 和盘古石，三家的软件各有优劣，但是核心功能大差不差，竞争点都集中在对数据预处理后的自动化分析上。
